config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'rooms/index'
  root to: "rooms#index"

  resources :users, only: :show
  resources :rooms do
    resources :comments, only: [:index, :new, :create]
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :artist
    validates :date
  end

  def self.search(search)
    if search != ''
      Room.where(['title LIKE? OR artist LIKE?', "%#{search}%", "%#{search}%"])

    else
      Room.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rooms
  has_many :comments

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comment = Comment.new
    @room = Room.find(params[:room_id])
    @comments = @room.comments.includes(:user).order('created_at DESC')
  end

  def create
    @room = Room.find(params[:room_id])
    @comment = @room.comments.new(comment_params)
    if @comment.save
      ActionCable.server.broadcast 'message_channel',
                                   content: @comment, name: @comment.user.name, time: @comment.created_at.strftime('%m月%d日%H:%M:%S'), id: @room.id
    else
      @comments = @room.comments.includes(:user).order('created_at DESC')
      render :index
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:message).merge(user_id: current_user.id, room_id: params[:room_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:edit, :update, :destroy]

  def index
    @rooms = Room.all
    @rooms = Room.includes(:user).order('created_at DESC')
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.create(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    redirect_root
  end

  def update
    redirect_root
    @room.update(room_params)
    if @room.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    redirect_root
    @room.destroy
    redirect_to root_path
  end

  def search
    @rooms = Room.search(params[:keyword]).order('created_at DESC')
    @keyword = params[:keyword]
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:title, :artist, :date).merge(user_id: current_user.id)
  end

  def redirect_root
    redirect_to root_path unless current_user.id == @room.user_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @rooms = user.rooms.order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment__bar">
  <div class="index_bar">
    <p>コメントを入力</p>
  </div>
  <div class="comment_form">
  <%= form_with model: [@room, @comment], class: 'comment_form', local: true do |f| %>
    <div class="comment-input">
      <%= f.text_field :message, placeholder: 'type a comment', class: 'comment-word', id: 'message_form' %>
    </div>
      <%= f.submit '送信', class: 'comment-submit', id: 'btn' %>
  <% end %>
  </div>
</div>

app/views/comments/_message.html.erb
<div id="messages">
</div>
<% @comments.each do |comments| %>
<div class="message-display">
  <div class="upper-message">
    <div class="message-user" >
      <!-- 投稿したユーザー名情報を出力する -->
      <%= link_to comments.user.name, user_path(comments.user.id), class: "user-name" %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= comments.created_at.strftime('%m月%d日%H:%M:%S')%>
    </div>
  </div>
  <div class="lower-message">
      <!-- 投稿したメッセージ内容を記述する -->
      <p><%= comments.message %></p>
  </div>
</div>
<% end %>

app/views/comments/_room.html.erb
<div class="comment_bar">
  <div class="user_name">
    <%= link_to "ようこそ" + current_user.name + "さん", user_path(current_user.id), class: "user__name" %>
  </div>
  <div class="comment_room">
    <div class="edit_bar">
      <p class="comment_post">
        タイトル：<%= @room.title %>
      </p>
      <% if current_user.id == @room.user.id %>
        <div class="edit_btn"><%= link_to "編集", edit_room_path(@room.id), class: :room__btn %></div>
      <% end %>
    </div>
    <div class="edit_bar">
      <p class="comment_post">
        アーティスト：<%= @room.artist %>
      </p>
    </div>
    <p class="comment_post">
      リリース日：<%= @room.date %>
    </p>
    <p class="comment_post">
      投稿者：<%= @room.user.name %>
    </p>
  </div>
  <%= link_to "戻る", root_path, class: :end_btn %>
</div>

app/views/comments/index.html.erb
<div class="wrapper">
  <div class="new_bar">
    <p>コメント投稿</p>
  </div>
  <%= render partial: 'room' %>
  <%= render partial: 'comment' %>
  <div class="comment_body">
    <%= render partial: 'message', locals: { comments: @comments} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MusicBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="main_header">
        <div class="main_title">
          <%= link_to image_tag("musicBoard.png", class: :main_logo), root_path %>
        </div>
          <% if user_signed_in? %>
          <div class="main_btn">
           <%= link_to "Logout", destroy_user_session_path, method: :delete, class: :nav__btn %>
           <%= link_to "New Post", new_room_path, class: :nav__btn %>
           </div>
          <% else %>
          <div class="main_btn">
            <%= link_to "Login", new_user_session_path, class: :nav__btn %>
            <%= link_to "Signup", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
      </div>
    </header>
    <%= yield %>
  </body>

  <footer>
  </footer>
</html>

app/views/rooms/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/rooms/_form.html.erb
<%= form_with model: room, local: true do |f|%>
<%# 部分テンプレートを呼び出し、インスタンスを渡して、エラー発生時にメッセージが表示されるようにしています %>
  <div class="inner">
  <%= render 'error_messages', model: f.object %>
<%# // 部分テンプレートを呼び出し、インスタンスを渡して、エラー発生時にメッセージが表示されるようにしています %>
    <div class="field">
      <%= f.label :title, "タイトル" %><br />
      <%= f.text_field :title, id:"prototype_title" %>
    </div>

    <div class="field">
      <%= f.label :artist, "アーティスト名" %><br />
      <%= f.text_field :artist, class: :form__text, id:"prototype_catch_copy" %>
    </div>

    <div class="field">
      <%= f.label :date, "リリース日" %><br />
      <%= f.date_field :date, class: :form__text, id:"prototype_concept" %>
    </div>

    <div class="actions">
      <%= f.submit "保存する", class: :form__btn  %>
    </div>
  </div>
<% end %>

app/views/rooms/_guide.html.erb
<div class="guide_logo">
<i class="fas fa-book"></i>
<ul class="edit_lists"><li id="guide" class="guide_btn">Guide</li></ul>
</div>
  <ul class="hidden" id="text">
    <li>・「投稿一覧ページ」に表示されるRoomの『タイトル』をクリックすると「コメントページ」へ遷移します。
      <br>　また、『投稿者』をクリックすると「その投稿者の投稿一覧ページ」へ遷移します。</li>
      <li>・各ページにある、『ようこそ(現在、自分がログインしているユーザー名)さん』をクリックすると自分の「投稿一覧ページ」へ遷移します。</li>
      <li>・自分が投稿したRoomにのみ『編集』ボタンが表示されます。
      <br>　また、自分のユーザーページにのみ『削除』ボタンが表示されます。</li>
      <li>・投稿一覧ページ上部にあるフォームに検索したいワード（タイトルまたはアーティスト名）を入力し検索すると条件に合ったRoomが表示されます。</li>
      <li>・ページ上部のロゴをクリックすると「投稿一覧ページ」へ遷移します。</li>
  </ul>

app/views/rooms/_rooms.html.erb
<div class="room">
  <div class="post">
    <div class="edit_bar">
      <div class="room_post">
        タイトル：<%= link_to room.title, room_comments_path(room), class: :room_url %>
      </div>
      <% if current_user.id == room.user.id %>
        <div class="edit_btn"><%= link_to "編集", edit_room_path(room.id), class: :room__btn %></div>
      <% end %>
    </div>
    <div class="edit_bar">
      <p class="room_post">
        アーティスト：<%= room.artist %>
      </p>
    </div>
      <p class="room_post">
        リリース日：<%= room.date %>
      </p>
      <p class="room_post">
        投稿者：<%= link_to room.user.name, user_path(room.user.id), class: :room_user %>
      </p>
  </div>
</div>

app/views/rooms/_search.html.erb
<div class="search_bar">
  <div class="index_bar">
    <p>投稿一覧</p>
  </div>
  <div class="search_form">
    <%= form_with(url: search_rooms_path, local: true, method: :get, class: "form-input") do |form| %>
    <%= form.text_field :keyword, placeholder: "Please enter a keyword", class: "form-keyword", value: @keyword %>
    <%= form.submit "検索", class: "form-submit" %>
    <% end %>
  </div>
  
</div>

app/views/rooms/edit.html.erb
<div class="wrapper">
<div class="new_bar">
    <p>投稿編集ページ</p>
</div>
<div class="user_name">
    <%= link_to "ようこそ" + current_user.name + "さん", user_path(current_user.id), class: "user__name" %>
</div>
<%= render partial: "form", locals: { room: @room } %>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <%= render partial: "search" %>
  <div class="top-bar">
    <div class="user_name">
      <%= link_to "ようこそ" + current_user.name + "さん", user_path(current_user.id), class: "user__name" %>
    </div>
    <div class="right_bar">
      <div class="guide">
        <%= render partial: "guide" %>
      </div>
    </div>
  </div>
<main class="main">
  <% @rooms.each do |room| %>
    <%= render partial: "rooms", locals: { room: room }%>
  <% end %>
</div>

app/views/rooms/new.html.erb
<div class="wrapper">
<div class="new_bar">
    <p>新規投稿</p>
</div>
<div class="user_name">
    <%= link_to "ようこそ" + current_user.name + "さん", user_path(current_user.id), class: "user__name" %>
</div>
<%= render partial: "form", locals: { room: @room } %>
</div>

app/views/rooms/search.html.erb
<div class="wrapper">
<%= render partial: "search" %>
<div class="user_name">
    <%= link_to "ようこそ" + current_user.name + "さん", user_path(current_user.id), class: "user__name" %>
</div>
<div class="contents row">
  <% @rooms.each do |room| %>
    <%= render partial: "rooms", locals: { room: room } %>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="wrapper">
<div class="show_user">
  <div class="show_bar">
    <p><%= @name + "さんの投稿一覧" %></p>
  </div>
  <% @rooms.each do |room| %>
      <div class="room">
  <div class="post">
    <div class="edit_bar">
      <div class="room_post">
        タイトル：<%= link_to room.title, room_comments_path(room), class: :room_url %>
      </div>
      <% if current_user.id == room.user.id %>
        <div class="edit_btn"><%= link_to "編集", edit_room_path(room.id), class: :room__btn %></div>
      <% end %>
    </div>
    <div class="edit_bar">
      <p class="room_post">
        アーティスト：<%= room.artist %>
      </p>
      <% if current_user.id == room.user.id %>
        <div><%= link_to "削除", room_path(room.id), method: :delete, class: :room__btn %></div>
      <% end %>
    </div>
      <p class="room_post">
        リリース日：<%= room.date %>
      </p>
      <p class="room_post">
        投稿者：<%= link_to room.user.name, user_path(room.user.id), class: :room_user %>
      </p>
  </div>
        
        
</div>

  <% end %>
</div>
</div>